[global]
username = "YOUR_SPOTIFY_USERNAME"
password_cmd = "cat /home/pi/.config/spotifyd/spotify_password"
device_name = "spotifyd-pi"
backend = "alsa"
volume_controller = "alsa"
use_mpris = false
autoplay = false
